### ISSUE TITLE
Desarrollo en API MID para ajuste del módulo de parametrización.

### ISSUE THREAD

**Issue by a52290451** [udistrital/polux_mid#15]
Se requiere realizar el desarrollo necesario en **polux_mid** para optimizar el módulo de parametrización en cuanto a la parametrización de tablas se refiere. Se debe tener en cuenta la creación o ajuste de EndPoints necesarios y las tareas que esto conlleve (acceso a tablas paramétricas, ajuste o creación de controladores, modelo de datos y helpers).

**Criterio de aceptación**

- [x] Creación de rama Feature de desarrollo en polux_mid.

**Nota**: Tomar en consideración el análisis realizado en "[Estudio del módulo de parametrización](https://github.com/udistrital/polux_cliente/issues/108)".

Tener en cuenta los [lineamientos](https://github.com/udistrital/lineamientos_oas) dispuestos por la OAS para la creación y carga de nuevas ramas en git.

**Comment by mantnicot** [comment]
Tablas las cuales se deben colocar en el despliegue del menu:

detalle
estado_asignatura_trabajo_grado
estado_espacio_academico_inscrito
estado_estudiante_trabajo_grado
estado_revision_trabajo_grado
estado_solicitud
estado_trabajo_grado
modalidad
pregunta
respuesta
rol_trabajo_grado
tipo_detalle                   
tipo_pregunta
tipo_solicitud

Se crearon dos archivos :

parametrización.js
parametrización.html

Se hizo lo siguiente pues esto es lo más eficiente para poder realizar el cliente, se tomo como base del modulo:
areas.js
areas.html

Al no tener modelo de negocio, trabaja directamente desde el cliente

Se agrego en el index.hmtl la ruta nueva

linea 208 -- <script src="scripts/controllers/administracion/parametrizacion.js"></script>

Se creo una ruta nueva  en ( app.js ) para acceder a la nueva vista y trabajar todo el concepto y pruebas 


Se creo la primera parte del controlador y ya se puede observar la lista y cambiar el estado de la misma 


Se esta trabajando en la inserción de cada parámetro pues como son diferentes tablas se debe crear una modal para cada una y así mismo realizar los mensajes de translate y creacion de menu por medio de 

https://pruebasconfiguracion.portaloas.udistrital.edu.co/

Pero no ha permitido la entrada, pero al ser un proceso sencillo se espera realizarse pronto



![Captura de pantalla de 2021-08-23 20-38-00](https://user-images.githubusercontent.com/85162258/130541612-d58ea3f0-5ebf-4fb7-b8fb-ba5bc3c9ca6d.png)

**Comment by mantnicot** [comment]
Se paso el desarrollo del POLUX_CRUD , en los siguiente commit subidos a develop

[Commit 1](https://github.com/udistrital/polux_crud/commit/1088f10c8b8a689227be972375628f8dd74def17)


[Commit 2](https://github.com/udistrital/polux_crud/commit/32ffbb4251d76ada236d27ed71018d7feafac14d)



[Commit 3](https://github.com/udistrital/polux_crud/commit/21794039719e8222d77cafd01839674196f54712)




[Commit 4](https://github.com/udistrital/polux_crud/commit/c0df4a6934e0b4f837092054813a3f0befb05f41)



[Commit 5](https://github.com/udistrital/polux_crud/commit/f160046e9bcc1972d2352b3f160cd5cb92dc0e68)



[Commit 6](https://github.com/udistrital/polux_crud/commit/87bf800d8cf65ec0bd7e50dabe4a80a70d6d8919)



[Commit 7](https://github.com/udistrital/polux_crud/commit/87019742e51e5ee23ca3e4cb48bb4d27c00accf5)



[Commit 8](https://github.com/udistrital/polux_crud/commit/5be6f72d117278357349991bb47b778769cfc059)



Se comienza el proceso de pruebas unitarias y usabilidad
